name: glints_twitter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: 3.0.1
  auto_size_text: 3.0.0
  font_awesome_flutter: 10.1.0
  equatable: ^2.0.5
  page_transition: 2.0.9
  flow_builder: 0.0.9
  flutter_spinkit: 5.1.0
  glints_twiter_firebase:
    path: packages/glints_twiter_firebase

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
