name: glints_twiter_firebase
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  built_collection: 5.1.1
  built_value: 8.4.0
  cloud_firestore: 3.2.1
  firebase_auth: 3.4.1
  firebase_core: 1.19.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
  build_runner: 2.2.0
  built_value_generator: 8.4.0
